name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: hello-world-python
  CUSTOM_TAG: ${{ secrets.CUSTOM_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:latest .

    - name: Tag image with custom tag
      run: |
        docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:latest $DOCKERHUB_USERNAME/$IMAGE_NAME:$CUSTOM_TAG

    - name: Push latest tag
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

    - name: Push custom tag
      run: |
        docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$CUSTOM_TAG
